### ISSUE TITLE
Merge type-instances correctly

### ISSUE THREAD

**Issue by waveform80** [waveform80/structa#19]
Currently, when a Dict with Field keys is merged with a Dict with, say, Scalar keys, the result duplicates the typed entries and the subsequent sort (intended for fields) fails (because Scalar entries are unsortable):

```python3
Traceback (most recent call last):                                                                                                                                           
  File "/home/dave/envs/structa/bin/structa", line 33, in <module>
    sys.exit(load_entry_point('structa', 'console_scripts', 'structa')())
  File "/home/dave/projects/structa/structa/ui/cli.py", line 30, in main
    structure = get_structure(config)
  File "/home/dave/projects/structa/structa/ui/cli.py", line 230, in get_structure
    result = analyzer.merge(struct)
  File "/home/dave/projects/structa/structa/analyzer.py", line 272, in merge
    return self._merge(struct)
  File "/home/dave/projects/structa/structa/analyzer.py", line 315, in _merge
    return path.with_content([
  File "/home/dave/projects/structa/structa/analyzer.py", line 316, in <listcomp>
    self._merge(item)
  File "/home/dave/projects/structa/structa/analyzer.py", line 310, in _merge
    return path.with_content([
  File "/home/dave/projects/structa/structa/analyzer.py", line 311, in <listcomp>
    DictField(self._merge(field.key), self._merge(field.value))
  File "/home/dave/projects/structa/structa/analyzer.py", line 310, in _merge
    return path.with_content([
  File "/home/dave/projects/structa/structa/analyzer.py", line 311, in <listcomp>
    DictField(self._merge(field.key), self._merge(field.value))
  File "/home/dave/projects/structa/structa/analyzer.py", line 305, in _merge
    DictField(self._merge(keys), self._merge(sum(
  File "/home/dave/projects/structa/structa/types.py", line 301, in __add__
    result = super().__add__(other)
  File "/home/dave/projects/structa/structa/types.py", line 248, in __add__
    result.content = [a + b for a, b in self._zip(other)]
  File "/home/dave/projects/structa/structa/types.py", line 248, in <listcomp>
    result.content = [a + b for a, b in self._zip(other)]
  File "/home/dave/projects/structa/structa/types.py", line 337, in __add__
    self.value + other.value)
  File "/home/dave/projects/structa/structa/types.py", line 305, in __add__
    result.content = sorted(result.content, key=attrgetter('key'))
TypeError: '<' not supported between instances of 'Str' and 'Str'
```

**Comment by waveform80** [comment]
Fixed in 7ce9b1ea3f8a31bfe9726dd958231fffc8878bd0
